- name: Initial setup ofHome Lab - Turing Pi 2 cluster
  hosts: nodes
  become: yes
  vars_prompt:
    - name: node_password
      prompt: "Enter the SSH password for the nodes"
      private: yes
  vars:
    ansible_ssh_pass: "{{ node_password }}"
    ansible_become_pass: "{{ node_password }}"
  tasks:
    - name: Set hostname for each node
      hostname:
        name: "{{ hostname }}"

    - name: Deploy SSH keys
      authorized_key:
        user: ubuntu
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present

    - name: Configure passwordless sudo for ubuntu user
      lineinfile:
        path: /etc/sudoers.d/90-ubuntu-nopasswd
        line: "ubuntu ALL=(ALL) NOPASSWD:ALL"
        create: yes
        mode: '0440'
        owner: root
        group: root
        validate: 'visudo -cf %s'
      become: yes

    - name: Update package cache and upgrade all packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Set static IP with Netplan
      template:
        src: templates/netplan.j2
        dest: /etc/netplan/01-netcfg.yaml
        mode: '0644'
      notify: Apply netplan

    - name: Reboot nodes to apply static IPs and hostname
      reboot:
        reboot_timeout: 300

  handlers:
    - name: Apply netplan
      command: netplan apply