- name: Set up K3s Kubernetes cluster
  hosts: k3s_cluster
  become: yes
  tasks:
    - name: Wait for nodes to be reachable with static IPs
      wait_for_connection:
        timeout: 300

    - name: Install K3s on server (node1)
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s
      when: inventory_hostname == 'node1'

    - name: Get K3s join token from server
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      when: inventory_hostname == 'node1'

    - name: Copy K3s token to local machine
      copy:
        content: "{{ hostvars['node1'].k3s_token.stdout }}"
        dest: /tmp/k3s_token
      delegate_to: localhost
      when: inventory_hostname == 'node1'

    - name: Install K3s on agents and join cluster
      shell: curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['node1'].ansible_host }}:6443 K3S_TOKEN={{ hostvars['node1'].k3s_token.stdout }} sh -
      args:
        creates: /usr/local/bin/k3s
      when: inventory_hostname in ['node2', 'node3']

    - name: Fetch kubeconfig from server
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./kubeconfig
        flat: yes
      when: inventory_hostname == 'node1'

- name: Install Helm on control machine
  hosts: localhost
  connection: local
  tasks:
    - name: Check if Helm is installed
      command: helm version
      register: helm_version
      ignore_errors: yes
    - name: Install Helm
      when: helm_version.rc != 0
      shell: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
      args:
        creates: /usr/local/bin/helm

- name: Set up Kubernetes Dashboard using Helm
  hosts: localhost
  connection: local
  tasks:
    - name: Add Kubernetes Dashboard Helm repository
      command: helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
      environment:
        KUBECONFIG: ./kubeconfig

    - name: Update Helm repositories
      command: helm repo update
      environment:
        KUBECONFIG: ./kubeconfig

    - name: Install Kubernetes Dashboard
      command: helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --namespace kubernetes-dashboard --create-namespace
      environment:
        KUBECONFIG: ./kubeconfig

    - name: Create admin user for Dashboard
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'files/dashboard-admin.yaml') }}"
        environment:
          KUBECONFIG: ./kubeconfig

    - name: Expose Dashboard on NodePort
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: kubernetes-dashboard
            namespace: kubernetes-dashboard
          spec:
            type: NodePort
            ports:
            - port: 443
              targetPort: 8443
              nodePort: 30000
            selector:
              k8s-app: kubernetes-dashboard
        environment:
          KUBECONFIG: ./kubeconfig

    - name: Get Dashboard token
      shell: kubectl -n kubernetes-dashboard describe secret $(kubectl -n kubernetes-dashboard get secret | grep admin-user | awk '{print $1}') | grep 'token:' | awk '{print $2}'
      register: dashboard_token
      environment:
        KUBECONFIG: ./kubeconfig

    - name: Display Dashboard access information
      debug:
        msg: "Access the Dashboard at https://{{ hostvars['node1'].ansible_host }}:30000 with token: {{ dashboard_token.stdout }}"